# Generated by Django 5.2.7 on 2025-10-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, null=True)),
                ('description', models.CharField(default=None, max_length=150, null=True)),
                ('price', models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
