# Generated by Django 5.2.7 on 2025-10-30 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBestProducts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyBestProducts.product')),
            ],
        ),
        migrations.CreateModel(
            name='TopList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyBestProducts.product')),
            ],
        ),
    ]
