# Generated by Django 5.2.8 on 2025-11-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBestProducts', '0002_mainlist_toplist'),
    ]

    operations = [
        migrations.CreateModel(
            name='basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, null=True)),
                ('count', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='toplist',
            name='product',
        ),
        migrations.DeleteModel(
            name='MainList',
        ),
        migrations.DeleteModel(
            name='TopList',
        ),
    ]
