# Generated by Django 5.2.8 on 2025-11-23 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBestProducts', '0003_basket_remove_toplist_product_delete_mainlist_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='basket',
        ),
    ]
