# Generated by Django 5.2.8 on 2025-11-24 17:32

from django.db import migrations, models
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(
                default=1,  # постав будь-який існуючий user_id, якщо є користувачі
                on_delete=models.CASCADE,
                to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
    ]
